"""Initial migration.

Revision ID: 65e641015e9e
Revises: 
Create Date: 2021-06-06 15:45:11.294596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.models import JsonEncodedList

revision = '65e641015e9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_connected_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('first_dev_name', sa.String(), nullable=False),
    sa.Column('second_dev_name', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('organisations', JsonEncodedList(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_connected_data')
    # ### end Alembic commands ###
